###服务端口号
server:
  port: 8100
###服务名称(服务注册到eureka名称,集群时名字要一致) 
spring:
    application:
        name: app-spring-eureka
###eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      ##集群、互相注册，此处注册到8200/8300
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
                  #,http://${eureka.instance.hostname}:8200/eureka/
                  #,http://${eureka.instance.hostname}:8300/eureka/
###因为自己是为注册中心，不需要自己注册自己false。集群时true
    register-with-eureka: false
###因为自己是为注册中心，不需要检索服务false。集群时true
    fetch-registry: false
  server: 
    ## 测试时关闭自我保护机制，保证不可用服务及时踢出      -----》手写ribbon负载均衡的时候，注释掉保护机制
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000